### ISSUE TITLE
Matlab Plot

### ISSUE THREAD

**Issue by mogilnickikevin** [frederic-bousefsaf/ippg-3dcnn#2]
Thanks for the great python code. Very easy to follow. I am having an issue as to what to plot for the predicted heart rate. It seems like I'm getting a 1x1x1x76 matlab map_p from the predict python code. I tried plotting the axis that that has length of 76 but it doesn't look like a prediction of the heart rate. It looks like it only goes from 0 to 76 instead of 55 to 240, with most of them having high probabilities at 76, so the max value. Just was curious if you could provide any info on how to use the results.mat.

**Comment by frederic-bousefsaf** [comment]
Thanks for your feedback. Regarding the dimensions of the map_p variable, I assume that you are predicting the Pulse Rate (PR) on a 60 x 25 x 25 image sequence. From this input, the prediction code will output a single PR estimation. You should therefore try to increase the size (number of frames and image dimensions) in order to get map_p dimensions that are >1.

I, in addition, attach a short Matlab code that should help you to compute and plot the PR series from map_p.

```
load('results.mat')
    
freq = linspace(55,240,75);
classes = [freq -1];

[~,max_predictions] = max(map_p,[],4);
max_predictions = classes(max_predictions);

iPR_wmean = zeros(1, size(max_predictions, 1));
edges_hist = [55:2.5:freq(end)+2.5];
for i=1:1:size(max_predictions, 1)
    N = histcounts(max_predictions(i,:,:), edges_hist);
    iPR_wmean(i) = sum(N .* freq) / sum(N);
end

stairs(iPR_wmean)
```

**Comment by mogilnickikevin** [comment]
Thanks!
